[[constraint]]
  name = "cloud.google.com/go"
  version = "0.16.0"

[[constraint]]
  name = "github.com/ChimeraCoder/anaconda"
  version = "1.0.0"

[[constraint]]
  name = "github.com/DataDog/datadog-go"
  version = "1.1.0"
